version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "c3:0d:5c:b0:da:c9:c4:92:ed:49:8d:14:e7:5f:02:f9"
      - setup_remote_docker:
          docker_layer_caching: true
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "sh deploy-web.sh"
  deploy_web:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "c3:0d:5c:b0:da:c9:c4:92:ed:49:8d:14:e7:5f:02:f9"
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "echo success"
dworkflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_web:
          requires:
            - build





              
