version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: docker build -t bcweb:latest .
      - run: docker login --username $DOCKER_USER --password $DOCKER_PW
      - run: docker tag bcweb:latest bcapp/bcweb:latest
      - run: docker push bcapp/bcweb:latest
  deploy_web:
    docker:
      - image: bcapp/bcweb:latest
    steps:
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP
      - run: docker-compose down
      - run: rm -rf bcclient
      - run: git clone http://github.com/begincoffees/bcclient.git bcclient
      - run: docker-compose up -d
workflows:
version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy_web:
          filters:
            branches:
              only: master
          requires:
            - build



              
