version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "17:d1:fc:c0:84:b6:c9:c4:c4:5b:d7:2a:80:be:5a:33"
      - setup_remote_docker:
          docker_layer_caching: true
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP -i ~/.ssh/known_hosts "echo 'bccicd SSH Successful'"
      # - run: docker build -t bcweb:latest .
      # - run: docker login --username $DOCKER_USER --password $DOCKER_PW
      # - run: docker tag bcweb:latest bcapp/bcweb:latest
      # - run: docker push bcapp/bcweb:latest
      # - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "echo 'bccicd SSH Succeeded'"
  deploy_web:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: echo 'Starting Deployment For bcweb'
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_web:
          requires:
            - build





              
