version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "d3:ab:3c:93:d7:0b:99:b8:a9:b9:c9:bd:e7:e6:65:5e"
      - setup_remote_docker:
          docker_layer_caching: true
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP 
      # - run: docker build -t bcweb:latest .
      # - run: docker login --username $DOCKER_USER --password $DOCKER_PW
      # - run: docker tag bcweb:latest bcapp/bcweb:latest
      # - run: docker push bcapp/bcweb:latest
      # - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "echo 'bccicd SSH Succeeded'"
  deploy_web:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: echo 'Starting Deployment For bcweb'
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_web:
          requires:
            - build





              
