version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "bf:3a:ee:84:d1:bf:ae:28:c6:44:ae:99:49:cd:3d:02"
      - setup_remote_docker:
          docker_layer_caching: true
      - run: ssh -oStrictHostKeyChecking=no -v $circleci@$DROPLET_IP >> $DOPW
      # - run: docker build -t bcweb:latest .
      # - run: docker login --username $DOCKER_USER --password $DOCKER_PW
      # - run: docker tag bcweb:latest bcapp/bcweb:latest
      # - run: docker push bcapp/bcweb:latest
      # - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "echo 'bccicd SSH Succeeded'"
  deploy_web:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: echo 'Starting Deployment For bcweb'
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_web:
          requires:
            - build





              
