version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "docker-compose up --build -d"
      - run: cd client && npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - run: 
workflows:
  version: 2
  build:
    jobs:
      - build
    # deploy:
    #     requires:
    #       - build
    #     filters:
    #       branches:
    #         only: master
    #     machine:
    #       image: circleci/classic:edge
    #       steps:
    #         - checkout
    #         - run: |
    #             docker login -u $DOCKER_USER -p $DOCKER_PASS
    #             docker build -t bcweb:latest bcapp/bcweb:latest .
    #             docker push bcweb:latest bcapp/bcweb:latest


              
