version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build -t bcgraph:latest .
      - run: docker login --username $DOCKER_USER --password $DOCKER_PW
      - run: docker tag bcgraph:latest bcapp/bcgraph:latest
      - run: docker push bcapp/bcgraph:latest
  deploy_web:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "c3:0d:5c:b0:da:c9:c4:92:ed:49:8d:14:e7:5f:02:f9"
      - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP
      - run: sh deploy-web.sh
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy_web:
          requires:
            - build





              
