version: '3'
services:
  circleci-web:
    container_name: circleci-web
    image: nginx:1.13.12-alpine
    restart: always
    ports:
      - "4040:80"
    build: . 
    networks:
      - bcapp
      - default
    volumes:
      - circleci-web:/usr/share/nginx/html
      - /usr/share/nginx/html
  circleci-web-whoami:
    container_name: circleci-web-whoami
    image: containous/whoami
    restart: always
    ports: 
      - "3030:80"
    networks:
      - bcapp
networks:
  bcapp: 
    external: true 