version: '3'
services:
  web:
    container_name: web
    image: nginx:1.13.12-alpine
    restart: always
    ports:
      - "5000:80"
    build: 
      context: ./client
      dockerfile: ./Dockerfile
    networks:
      - bcapp
    volumes:
      - web:/usr/share/nginx/html
      - /usr/share/nginx/html
  whoami:
    container_name: bcwhoami
    image: containous/whoami
    restart: always
    ports: 
      - "3000:80"
    networks:
      - bcapp
volumes:
  web:
networks:
  bcapp: 
    external: true 