version: '3'
services:
  bcweb:
    container_name: bcweb
    image: nginx:1.13.12-alpine
    restart: always
    ports:
      - "3000:80"
    networks:
      - bcapp-staging
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - bcweb:/usr/share/nginx/html
      - /usr/share/nginx/html
    labels:
      - traefik.backend=web
      - traefik.frontend.rule=Host:client.web
      - traefik.docker.network=bcapp-staging
      - traefik.port=80
  bcgraph:
    container_name: bcgraph
    image: node:8.11.1-alpine
    build: 
      context: ./bcgraph
      dockerfile: ./Dockerfile
    command: npm start
    restart: always
    ports: 
      - '6006:6006'
    volumes:
      - bcgraph:/usr/app/bcgraph
      - /usr/app/bcgraph
    networks:
      - bcapp-staging
    labels:
      - "traefik.frontend.rule=Host:bcgraph.docker.localhost"
      - 'traefik.port=6006'
  bcproxy:
    container_name: proxy
    image: traefik
    command: --api --docker
    networks:
      - bcapp-staging  
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - bcweb:/usr/share/nginx/html
      - bcgraph:/usr/app/bcgraph
    labels:
      - traefik.frontend.rule=Host:bcapp.health
  whoami2:
    container_name: whoami
    image: emilevauge/whoami
    networks:
      - bcapp-staging
    labels:
      - "traefik.backend=whoami"
      - "traefik.frontend.rule=Host:whoami.docker.localhost"
volumes:
  bcweb:
  bcgraph:
networks:
  bcapp-staging:
    external: true 