version: '3'
services:
  web:
    container_name: web 
    image: nginx:1.13.12-alpine
    restart: always
    ports:
      - "3000:80"
    build: . 
    networks:
      - bcapp
      - default
    volumes:
      - .:/usr/share/nginx/html
      - /usr/share/nginx/html
  whoami-web:
    container_name: whoami-web 
    image: containous/whoami
    restart: always
    ports: 
      - "3030:80"
volumes:
  web:
networks:
  bcapp:
    external: true 