defaultEntryPoints = ["http", "https"]

endpoint = "unix:///var/run/docker.sock"

domain = "docker.localhost"

watch = true

exposedByDefault = true


usebindportip = true


swarmMode = true


swarmModeRefreshSeconds = 15


network = "bcapp"



[entryPoints]
  [entryPoints.http]
    address = ":80"
    compress = true

    [entryPoints.https.whitelist]
      sourceRange = ["127.0.0.1", "172.20.0.1","172.20.0.2","172.20.0.3", "172.20.0.4"]
      useXForwardedFor = true

    [entryPoints.https.tls]
      minVersion = "VersionTLS12"
      cipherSuites = [
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_RSA_WITH_AES_256_GCM_SHA384"
       ]
      [[entryPoints.https.tls.certificates]]
        certFile = "path/to/my.cert"
        keyFile = "path/to/my.key"
      [[entryPoints.https.tls.certificates]]
        certFile = "path/to/other.cert"
        keyFile = "path/to/other.key"
      # ...
      [entryPoints.https.tls.clientCA]
        files = ["path/to/ca1.crt", "path/to/ca2.crt"]
        optional = false

    [entryPoints.https.auth]
      headerField = "X-httpsAuth-User"
      [entryPoints.https.auth.basic]
        removeHeader = false
        users = [
          "test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/",
          "test2:$apr1$d9hr9HBB$4HxwgUir3HP4EsggP/QNo0",
        ]

    [entryPoints.https.proxyProtocol]
      insecure = true
      trustedIPs = ["172.20.0.2:80"]

    [entryPoints.https.forwardedHeaders]
      trustedIPs = ["172.20.0.2:80"]