version: '3'
services:
  server:
    container_name: bcapi
    command: npm start
    restart: always
    build: .
    ports:
      - "6006:6006"
    volumes:
      - .:/usr/app/    
volumes:
  server: